### PR TITLE
Fix "Failed to parse json" on "npm install"

### LINKED ISSUE #13: npm treats package.json as invalid by default
npm was complaining that package.json is invalid
```
npm ERR! Failed to parse json
npm ERR! Unexpected token } in JSON at position 554 while parsing near '...nse": "Apache-2.0",
npm ERR! }
npm ERR! '
npm ERR! File: /tmp/matrix-appservice-tg/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

It's easily fixed by removing a trailing comma from the "license" line

### PR DESCRIPTION
**Pull request by Hi-Angel**
Fixes: https://github.com/matrix-org/matrix-appservice-tg/issues/13

### CODE REVIEW

**Comment by tulir** [comment]
Duplicate of #14

Also, this project is dead and hasn't really ever worked. The main Matrix-Telegram bridge software is at https://github.com/tulir/mautrix-telegram

**Comment by Hi-Angel** [comment]
> Also, this project is dead and hasn't really ever worked. The main Matrix-Telegram bridge software is at https://github.com/tulir/mautrix-telegram

That's funny, I was just writing an issue to deprecate this in preference of the later 
Screenshot_20190507_020144 but got distracted by something.

**Comment by tulir** [comment]
There's also a PR to add a notice to the README, but that hasn't been merged either since nobody accepts PRs: #15

**Comment by Hi-Angel** [comment]
Thanks! I sent the issue anyway as I think there's a probability that someone may not notice either the PR or the issue. Mentioned in PR that it fixes the report though.

**Pull request closed without merging**
