### PR TITLE
Put "on hold" notice into readme

### PR DESCRIPTION
**Pull request by Valodim**
It seems this repository isn't currently maintained. Add a note about that, and helpfully point users to the excellent mautrix-telegram bridge, which is probably what they are looking for.

### CODE REVIEW

**Comment by Hi-Angel** [comment]
Fixes: https://github.com/matrix-org/matrix-appservice-tg/issues/17

**Comment by jaywink** [comment]
Hi @Valodim ! Thanks for your contribution. Even though it's a readme fix, we require signing off on all commits to indicate acceptance of the [DCO](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off). All you need to do is amend the commit with `Signed-off-by: Your Name <your@email.example.org>` to indicate acceptance, then we can merge your commit.

Good to get a note in the readme, thanks for jumping on this :+1:

**Comment by Valodim** [comment]
Yo.

**Review by jaywink — APPROVED** [review]
Thanks!

**Pull request merged**
